In [12]:
#!pip install numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])  # 1D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

my_list = [1, 2, 3, 4, 5]

np_array = np.array(my_list)

In [3]:
np.zeros((3, 3))   # 3x3 matrix of zeros
np.ones((2, 2))    # 2x2 matrix of ones
np.full((2, 2), 9) # 2x2 matrix filled with 9
np.eye(3)          # 3x3 identity matrix
np.random.rand(3, 3) # 3x3 matrix with random values from 0 to 1
np.random.randint(0, 10, (2, 2)) # Random integers between 0 and 10
np.linspace(0, 10, 5) # 5 evenly spaced numbers from 0 to 10
np.arange(0, 10, 2) # Similar to range(), but returns an array

array([0, 2, 4, 6, 8])

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape:',arr.shape)   # (2, 3) → 2 rows, 3 columns
print('Number of elements:',arr.size )   # 6 → Total number of elements
print('Data type:',arr.dtype)  # dtype('int32') → Data type
print('Dimensions:',arr.ndim ) # 2 → Number of dimensions


Shape: (2, 3)
Number of elements: 6
Data type: int32
Dimensions: 2


In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])     # 20 (indexing)
print(arr[1:4])   # [20 30 40] (slicing)
print(arr[:3])    # [10 20 30] (first 3 elements)
print(arr[::-1])  # [50 40 30 20 10] (reverse order)

20
[20 30 40]
[10 20 30]
[50 40 30 20 10]


In [6]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[1, 2])  # 6 → Access element at row 1, column 2
print(arr2d[1, :])  # [4 5 6] → All elements in row 1
print(arr2d[:, 1])  # [2 5 8] → All elements in column 1

6
[4 5 6]
[2 5 8]


In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)  # [5 7 9]
print(arr1 - arr2)  # [-3 -3 -3]
print(arr1 * arr2)  # [4 10 18]
print(arr1 / arr2)  # [0.25 0.4 0.5]
print(arr1 ** 2)    # [1 4 9] (Element-wise squaring)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [8]:
arr = np.array([1, 2, 3, 4])
print(np.sqrt(arr))  # Square root
print(np.exp(arr))   # Exponential
print(np.log(arr))   # Logarithm
print(np.sin(arr))   # Sine function
print(np.cos(arr))   # Cosine function
print(np.sum(arr))   # Sum of elements
print(np.mean(arr))  # Mean
print(np.std(arr))   # Standard deviation
print(np.max(arr))   # Maximum
print(np.min(arr))   # Minimum


[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
10
2.5
1.118033988749895
4
1


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr.reshape(3, 2)  # Reshape into 3x2 matrix
arr.flatten()      # Convert multi-dimensional array into 1D

array([1, 2, 3, 4, 5, 6])

In [10]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25
print(arr[mask])  # [30 40 50] (Only elements greater than 25)


[30 40 50]


In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication
print(np.linalg.inv(A))  # Inverse of matrix A
print(np.linalg.det(A))  # Determinant of matrix A
print(np.linalg.eig(A))  # Eigenvalues & Eigenvectors


[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
